# -*- coding: utf-8 -*-
 
import sys
import salome

salome.salome_init()
theStudy = salome.myStudy

import salome_notebook
notebook = salome_notebook.NoteBook(theStudy)

### GEOM component
import GEOM
from salome.geom import geomBuilder
import SALOMEDS
import datetime, math

dateStart = datetime.datetime.now()

geompy = geomBuilder.New(theStudy)

# ajout du chemin de la bibliothèque
import inspect, os
scriptFullPathName = inspect.getfile(inspect.currentframe())
scriptDir = os.path.abspath(os.path.dirname(scriptFullPathName))
libDir = os.path.abspath('/home/moi/data/mypythonlib')
if (not any(libDir in pathItem for pathItem in sys.path)):  # ne rajoute le chemin que si nécessaire
  sys.path.append(libDir)
import ebt_3d


# erase all ------------
nb = theStudy.NewBuilder()
for compName in ["SMESH", "GEOM"]:
  comp = salome.myStudy.FindComponent(compName)
  if comp:
    iterator = salome.myStudy.NewChildIterator(comp)
    while iterator.More():
      sobj = iterator.Value()
      iterator.Next()
      nb.RemoveObjectWithChildren(sobj)

salome.sg. EraseAll()

O = geompy.MakeVertex(0, 0, 0)
OX = geompy.MakeVectorDXDYDZ(1, 0, 0)
OY = geompy.MakeVectorDXDYDZ(0, 1, 0)
OZ = geompy.MakeVectorDXDYDZ(0, 0, 1)
OXm = geompy.MakeVectorDXDYDZ(-1, 0, 0)
OYm = geompy.MakeVectorDXDYDZ(0, -1, 0)
OZm = geompy.MakeVectorDXDYDZ(0, 0, -1)
LCS_O = geompy.MakeMarkerPntTwoVec(O, OX, OY)
geompy.addToStudy( LCS_O, "LCS_O" )

geompy.addToStudy( O, 'O' )
geompy.addToStudy( OX, 'OX' )
geompy.addToStudy( OY, 'OY' )
geompy.addToStudy( OZ, 'OZ' )



# test
meanThreadRadius = 6.375
pitch = 1.5
height = 15.
bBolt = True # False #
if bBolt:
  nonThreadRadius = 0 #meanThreadRadius -2.
else:
  nonThreadRadius = meanThreadRadius +2.
threadAngle = 90.
nbThreads = 1
spacetBetweenThread =  0 # pitch / float(nbThreads) / 2.
smoothStartLength = 0
smoothEndLength   = pitch
rightHanded = True
MakeFuse    = True # False #

screw = makeNutBolt2(geompy,
                     meanThreadRadius = meanThreadRadius,
                     pitch = pitch,
                     height = height,
                     bBolt = bBolt,
                     nonThreadRadius = nonThreadRadius,
                     threadAngle = threadAngle,
                     nbThreads = nbThreads,
                     spacetBetweenThread = spacetBetweenThread,
                     smoothStartLength = smoothStartLength,
                     smoothEndLength   = smoothEndLength,
                     rightHanded = rightHanded,
                     MakeFuse = MakeFuse)

geompy.addToStudy(screw, "screw")
